import { useEffect, useState } from 'react'
import { createAvailability, getAvailability, updateAvailability } from '../api/availability'
import DataTable from '../components/DataTable'
import LoadingState from '../components/LoadingState'
import { PageIntro } from './Dashboard'

export default function InstructorAvailability() { const [rows, setRows] = useState(null); const [form, setForm] = useState({ machine_id: '', start_time: '', end_time: '' }); const [error, setError] = useState(''); const load = () => getAvailability().then(setRows).catch((e) => setError(e.message)); useEffect(load, [])
  const submit = async (e) => { e.preventDefault(); try { await createAvailability({ ...form, machine_id: form.machine_id || null }); setForm({ machine_id: '', start_time: '', end_time: '' }); load() } catch (err) { setError(err.message) } }
  if (!rows) return <PageIntro eyebrow="SUPERVISION" title="Availability"><LoadingState /></PageIntro>
  return <PageIntro eyebrow="SUPERVISION" title="Availability" subtitle="Publish the windows when you can supervise machines.">{error && <div className="alert error">{error}</div>}<form className="panel inline-form" onSubmit={submit}><input placeholder="Machine ID (optional for general availability)" value={form.machine_id} onChange={(e) => setForm({ ...form, machine_id: e.target.value })} /><label className="field compact"><span>Starts</span><input required type="datetime-local" value={form.start_time} onChange={(e) => setForm({ ...form, start_time: e.target.value })} /></label><label className="field compact"><span>Ends</span><input required type="datetime-local" value={form.end_time} onChange={(e) => setForm({ ...form, end_time: e.target.value })} /></label><button className="primary-button">Add window</button></form><DataTable rows={rows} empty="No availability windows yet." columns={[{ key: 'machine_id', label: 'Machine', render: (r) => r.machine_id || 'General' }, { key: 'start_time', label: 'Starts', render: (r) => new Date(r.start_time).toLocaleString() }, { key: 'end_time', label: 'Ends', render: (r) => new Date(r.end_time).toLocaleString() }, { key: 'actions', label: '', render: (r) => <button className="table-action" onClick={async () => { try { await updateAvailability(r.id, { ...r, start_time: r.start_time, end_time: r.end_time }); load() } catch (e) { setError(e.message) } }}>Save current</button> }]} /></PageIntro> }
