import { useEffect, useState } from 'react'
import { useSearchParams, useNavigate } from 'react-router-dom'
import { getComponents } from '../api/components'
import { getMachines } from '../api/machines'
import { createBooking } from '../api/bookings'
import { PageIntro } from './Dashboard'
import LoadingState from '../components/LoadingState'
import StatusBadge from '../components/StatusBadge'

export default function StudentBooking() {
  const [searchParams] = useSearchParams(); const navigate = useNavigate(); const [resources, setResources] = useState([]); const [form, setForm] = useState({ target_type: searchParams.get('type') || 'machine', target_id: searchParams.get('id') || '', start_time: '', end_time: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState({ type: '', text: '' })
  useEffect(() => { Promise.all([getComponents(), getMachines()]).then(([components, machines]) => setResources([...components.map((x) => ({ ...x, kind: 'component' })), ...machines.map((x) => ({ ...x, kind: 'machine' }))])).catch((err) => setMessage({ type: 'error', text: err.message })).finally(() => setLoading(false)) }, [])
  const available = resources.filter((item) => item.kind === form.target_type && item.status === 'available')
  const submit = async (event) => { event.preventDefault(); setSaving(true); setMessage({ type: '', text: '' }); try { await createBooking(form); setMessage({ type: 'success', text: 'Booking submitted. It is now pending approval.' }); setTimeout(() => navigate('/bookings'), 700) } catch (err) { setMessage({ type: 'error', text: err.message }) } finally { setSaving(false) } }
  return <PageIntro eyebrow="RESERVE TIME" title="Book a resource" subtitle="Choose a clear window. The workshop will take care of the rest.">{loading ? <LoadingState /> : <div className="form-layout"><form className="panel form-panel" onSubmit={submit}><div className="form-section"><span className="eyebrow">01 / RESOURCE</span><h3>What are you building with?</h3><div className="segmented"><button type="button" className={form.target_type === 'machine' ? 'selected' : ''} onClick={() => setForm({ ...form, target_type: 'machine', target_id: '' })}>Machines</button><button type="button" className={form.target_type === 'component' ? 'selected' : ''} onClick={() => setForm({ ...form, target_type: 'component', target_id: '' })}>Components</button></div><select required value={form.target_id} onChange={(e) => setForm({ ...form, target_id: e.target.value })}><option value="">Select an available {form.target_type}</option>{available.map((item) => <option key={item.id} value={item.id}>{item.name}{item.requires_instructor ? ' · instructor required' : ''}</option>)}</select>{form.target_id && <div className="selected-resource"><StatusBadge status="available" /><strong>{resources.find((item) => String(item.id) === String(form.target_id) && item.kind === form.target_type)?.name}</strong></div>}</div><div className="form-section"><span className="eyebrow">02 / TIME WINDOW</span><h3>When will you need it?</h3><div className="date-grid"><label className="field"><span>Starts</span><input required type="datetime-local" value={form.start_time} onChange={(e) => setForm({ ...form, start_time: e.target.value })} /></label><label className="field"><span>Ends</span><input required type="datetime-local" value={form.end_time} onChange={(e) => setForm({ ...form, end_time: e.target.value })} /></label></div></div>{message.text && <div className={`alert ${message.type}`}>{message.text}</div>}<button className="primary-button" disabled={saving}>{saving ? 'Submitting...' : 'Submit booking'} <span>→</span></button></form><aside className="booking-note"><span className="note-icon">✦</span><h3>Good to know</h3><p>Bookings start as pending. Machines that need supervision require instructor approval and a matching availability window.</p><div className="note-rule" /><small>Only available resources can be reserved.</small></aside></div>}</PageIntro>
}
